site_name: Fixie Developer Portal
site_description: API and SDK documentation for Fixie
site_url: https://fixie.ai/

# theme:
#   palette:
#   - media: "(prefers-color-scheme: light)"
#     scheme: default
#     primary: teal
#     accent: purple
#     toggle:
#       icon: material/weather-sunny
#       name: Switch to dark mode
#   - media: "(prefers-color-scheme: dark)"
#     scheme: slate
#     primary: black
#     accent: lime
#     toggle:
#       icon: material/weather-night
#       name: Switch to light mode

theme:
    name: cinder
    logo: assets/fixie-logo.png
    favicon: assets/fixie-logo.png
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: black
        accent: lime
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'
#    features:
#      - content.code.annotate
#      - navigation.tabs
#      - navigation.tabs.sticky
#      - navigation.top

repo_name: fixie-ai/fixie-sdk
repo_url: https://github.com/fixie-ai/fixie-sdk
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Architecture: 'architecture.md'
    - Agents:
      - Agent QuickStart: 'agent-quickstart.md'
      - Agent Protocol: 'agent-protocol.md'
    - Python SDK:
        - Client API: 'api-client.md'
        - Agent API: 'api-agents.md'
    - CLI: 'cli.md'
    - GraphQL: 'https://app.fixie.ai/static/docs/index.html'


markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkdocs-click

extra_css:
    - css/custom.css

plugins:
  - search
  - mkdocstrings
