site_name: Fixie Developer Portal
site_description: API and SDK documentation for Fixie
site_url: https://fixie.ai/

theme:
    logo: assets/fixie-logo.png
    favicon: assets/fixie-logo.png
    name: 'readthedocs'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'black'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'
    features:
        - navigation.sections
        - navigation.tabs

repo_name: fixie-ai/fixie-sdk
repo_url: https://github.com/fixie-ai/fixie-sdk
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Fixie Architecture: 'architecture.md'
    - Agent QuickStart: 'agent-quickstart.md'
    - Python SDK Reference:
        - Client API: 'api-client.md'
        - Agent API: 'api-agents.md'
    - CLI Reference: 'cli.md'
    - Protocol reference: 'agent-protocol.md'
    - GraphQL Reference: 'https://app.fixie.ai/static/docs/index.html'


markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkdocs-click

extra_css:
    - css/custom.css

plugins:
  - search
  - mkdocstrings
